# Generated by Django 6.0.4 on 2026-05-04 05:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('compras', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('days_due', models.PositiveIntegerField(default=0, verbose_name='Dias de credito')),
                ('is_cash_sale', models.BooleanField(default=False, verbose_name='Es contado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condicion comercial',
                'verbose_name_plural': 'Condiciones comerciales',
                'ordering': ['days_due', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medio de pago',
                'verbose_name_plural': 'Medios de pago',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('draft', 'DRAFT - Proforma'), ('reserved', 'RESERVED - Reserva'), ('ordered', 'ORDERED - Pedido'), ('confirmed', 'CONFIRMED - Venta aceptada'), ('delivered', 'DELIVERED - Entregado'), ('cancelled', 'CANCELLED - Cancelado'), ('proforma', 'Proforma'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='confirmada', max_length=20, verbose_name='Estado')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulacion')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('received_by_name', models.CharField(blank=True, max_length=120, verbose_name='Recibido por')),
                ('received_by_doc', models.CharField(blank=True, max_length=40, verbose_name='Documento de quien recoge')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Observaciones de entrega')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('payment_type', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('qr', 'QR'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20, null=True, verbose_name='Tipo de pago (legacy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backorder_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorder_sales', to='compras.purchase', verbose_name='Compra de respaldo (backorder)')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canceled_sales', to=settings.AUTH_USER_MODEL, verbose_name='Anulada por')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.client', verbose_name='Cliente')),
                ('commercial_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='ventas.commercialcondition', verbose_name='Condicion comercial')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_sales', to=settings.AUTH_USER_MODEL, verbose_name='Entregada por')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Referencia')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_payments', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ventas.paymentmethod', verbose_name='Medio de pago')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ventas.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('ref_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ref. m²')),
                ('cajas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cajas')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.product', verbose_name='Producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
                'ordering': ['sale'],
                'unique_together': {('sale', 'product')},
            },
        ),
    ]
