# Generated by Django 6.0.4 on 2026-04-08 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_add_seller_and_status_to_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulacion'),
        ),
        migrations.AddField(
            model_name='sale',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canceled_sales', to=settings.AUTH_USER_MODEL, verbose_name='Anulada por'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('proforma', 'Proforma'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='confirmada', max_length=20, verbose_name='Estado'),
        ),
    ]
