# Generated by Django 6.0.4 on 2026-05-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_saledetail_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='cajas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cajas'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='ref_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ref. m²'),
        ),
    ]
