# Generated by Django 6.0.4 on 2026-05-02 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_saledetail_ref_m2_cajas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_sales', to=settings.AUTH_USER_MODEL, verbose_name='Entregada por'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='Observaciones de entrega'),
        ),
        migrations.AddField(
            model_name='sale',
            name='received_by_doc',
            field=models.CharField(blank=True, max_length=40, verbose_name='Documento de quien recoge'),
        ),
        migrations.AddField(
            model_name='sale',
            name='received_by_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Recibido por'),
        ),
    ]
