# Generated by Django 6.0.4 on 2026-05-04 03:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_commercial_data(apps, schema_editor):
    CommercialCondition = apps.get_model('ventas', 'CommercialCondition')
    PaymentMethod = apps.get_model('ventas', 'PaymentMethod')
    Sale = apps.get_model('ventas', 'Sale')

    cash_condition, _ = CommercialCondition.objects.get_or_create(
        code='cash_0',
        defaults={
            'name': 'Contado (0 dias)',
            'days_due': 0,
            'is_cash_sale': True,
            'is_active': True,
        },
    )
    credit_7, _ = CommercialCondition.objects.get_or_create(
        code='credit_7',
        defaults={
            'name': 'Credito 7 dias',
            'days_due': 7,
            'is_cash_sale': False,
            'is_active': True,
        },
    )
    CommercialCondition.objects.get_or_create(
        code='credit_15',
        defaults={
            'name': 'Credito 15 dias',
            'days_due': 15,
            'is_cash_sale': False,
            'is_active': True,
        },
    )
    CommercialCondition.objects.get_or_create(
        code='credit_30',
        defaults={
            'name': 'Credito 30 dias',
            'days_due': 30,
            'is_cash_sale': False,
            'is_active': True,
        },
    )

    for code, name in (
        ('cash', 'Efectivo'),
        ('qr', 'QR'),
        ('transferencia', 'Transferencia'),
        ('tarjeta', 'Tarjeta'),
    ):
        PaymentMethod.objects.get_or_create(
            code=code,
            defaults={
                'name': name,
                'is_active': True,
            },
        )

    for sale in Sale.objects.filter(commercial_condition__isnull=True):
        default_condition = cash_condition if sale.payment_type else credit_7
        sale.commercial_condition = default_condition
        sale.due_date = sale.date.date()
        sale.save(update_fields=['commercial_condition', 'due_date'])


def unseed_commercial_data(apps, schema_editor):
    CommercialCondition = apps.get_model('ventas', 'CommercialCondition')
    PaymentMethod = apps.get_model('ventas', 'PaymentMethod')
    PaymentMethod.objects.filter(code__in=['cash', 'qr', 'transferencia', 'tarjeta']).delete()
    CommercialCondition.objects.filter(code__in=['cash_0', 'credit_7', 'credit_15', 'credit_30']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_sale_delivered_at_sale_delivered_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('days_due', models.PositiveIntegerField(default=0, verbose_name='Dias de credito')),
                ('is_cash_sale', models.BooleanField(default=False, verbose_name='Es contado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condicion comercial',
                'verbose_name_plural': 'Condiciones comerciales',
                'ordering': ['days_due', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medio de pago',
                'verbose_name_plural': 'Medios de pago',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('qr', 'QR'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20, null=True, verbose_name='Tipo de pago (legacy)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT - Proforma'), ('reserved', 'RESERVED - Reserva'), ('ordered', 'ORDERED - Pedido'), ('confirmed', 'CONFIRMED - Venta aceptada'), ('delivered', 'DELIVERED - Entregado'), ('cancelled', 'CANCELLED - Cancelado'), ('proforma', 'Proforma'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='confirmada', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='commercial_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='ventas.commercialcondition', verbose_name='Condicion comercial'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Referencia')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_payments', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ventas.sale', verbose_name='Venta')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ventas.paymentmethod', verbose_name='Medio de pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.RunPython(seed_commercial_data, unseed_commercial_data),
    ]
