# Generated by Django 6.0.4 on 2026-05-04 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_purchase_invoice_number_alter_purchase_supplier'),
        ('ventas', '0006_commercialcondition_paymentmethod_sale_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='backorder_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorder_sales', to='compras.purchase', verbose_name='Compra de respaldo (backorder)'),
        ),
    ]
