# Generated by Django 6.0.4 on 2026-04-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Username reportado')),
                ('event_type', models.CharField(choices=[('login_success', 'Inicio de sesion exitoso'), ('login_failed', 'Intento fallido'), ('logout', 'Cierre de sesion')], max_length=20, verbose_name='Tipo de evento')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Direccion IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evento')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento de acceso',
                'verbose_name_plural': 'Eventos de acceso',
                'ordering': ['-created_at'],
            },
        ),
    ]