# Generated by Django 6.0.4 on 2026-04-07 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_product_code_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3, verbose_name='Tipo')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('reference', models.CharField(max_length=120, verbose_name='Referencia')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='productos.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
