# Generated by Django 6.0.4 on 2026-05-02 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3, verbose_name='Tipo')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('reference', models.CharField(max_length=120, verbose_name='Referencia')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_movements', to='productos.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='movimientos.inventorymovement', verbose_name='Movimiento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_details', to='productos.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de movimiento',
                'verbose_name_plural': 'Detalles de movimiento',
            },
        ),
    ]
