# Generated by Django 6.0.4 on 2026-04-07 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
        ('productos', '0002_product_code_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_movements', to='productos.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.CreateModel(
            name='InventoryMovementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='movimientos.inventorymovement', verbose_name='Movimiento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_details', to='productos.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de movimiento',
                'verbose_name_plural': 'Detalles de movimiento',
            },
        ),
    ]
