# Generated by Django 6.0.4 on 2026-05-04 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Acabado',
                'verbose_name_plural': 'Acabados',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Formato',
                'verbose_name_plural': 'Formatos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndicacionesUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Indicaciones de uso',
                'verbose_name_plural': 'Indicaciones de uso',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='M2Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, unique=True, verbose_name='Valor (m²)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'm² por caja',
                'verbose_name_plural': 'm² por caja',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock')),
                ('stock_reservado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock reservado')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock mínimo')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acabado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.acabado', verbose_name='Acabado')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.category', verbose_name='Categoria')),
                ('formato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.formato', verbose_name='Formato')),
                ('indicaciones_uso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.indicacionesuso', verbose_name='Indicaciones de uso')),
                ('metros_cuadrados_por_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.m2caja', verbose_name='m² por caja')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
    ]
