# Generated by Django 6.0.4 on 2026-05-02 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Acabado',
                'verbose_name_plural': 'Acabados',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Formato',
                'verbose_name_plural': 'Formatos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndicacionesUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Indicaciones de uso',
                'verbose_name_plural': 'Indicaciones de uso',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='M2Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, unique=True, verbose_name='Valor (m²)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'm² por caja',
                'verbose_name_plural': 'm² por caja',
                'ordering': ['value'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='acabado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.acabado', verbose_name='Acabado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='formato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.formato', verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='product',
            name='indicaciones_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.indicacionesuso', verbose_name='Indicaciones de uso'),
        ),
        migrations.AlterField(
            model_name='product',
            name='metros_cuadrados_por_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.m2caja', verbose_name='m² por caja'),
        ),
    ]
