# Generated by Django 6.0.4 on 2026-04-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='acabado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Acabado'),
        ),
        migrations.AddField(
            model_name='product',
            name='formato',
            field=models.CharField(blank=True, max_length=100, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='product',
            name='indicaciones_uso',
            field=models.TextField(blank=True, verbose_name='Indicaciones de uso'),
        ),
        migrations.AddField(
            model_name='product',
            name='metros_cuadrados_por_caja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='m² por caja'),
        ),
    ]
