# Generated by Django 6.0.4 on 2026-04-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen'),
        ),
    ]
