# Generated by Django 6.0.4 on 2026-05-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_acabado_formato_indicacionesuso_m2caja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock'),
        ),
    ]
