# Generated by Django 6.0.4 on 2026-04-27 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_product_acabado_product_formato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
