# Generated by Django 6.0.4 on 2026-04-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_product_brand_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Color'),
        ),
    ]
