# Generated by Django 6.0.4 on 2026-05-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_reservado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock reservado'),
        ),
    ]
