# Generated by Django 6.0.4 on 2026-04-08 02:09

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('type', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('reference', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('gasto', 'Gasto')], max_length=20, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
