# Generated by Django 6.0.4 on 2026-05-04 05:05

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('type', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('reference', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('gasto', 'Gasto')], max_length=20, verbose_name='Referencia')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('qr', 'QR'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('no_aplica', 'No aplica')], default='no_aplica', max_length=20, verbose_name='Medio de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashBoxClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo inicial')),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ingresos')),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Egresos')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo de cierre')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrada')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cierre diario de caja',
                'verbose_name_plural': 'Cierres diarios de caja',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
