# Generated by Django 6.0.4 on 2026-04-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_cashboxclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('qr', 'QR'), ('transferencia', 'Transferencia'), ('no_aplica', 'No aplica')], default='no_aplica', max_length=20, verbose_name='Medio de pago'),
        ),
    ]
