from django.urls import path

from .views import (
    AcabadoCreateView,
    AcabadoDeleteView,
    AcabadoListView,
    AcabadoUpdateView,
    BrandCreateView,
    BrandDeleteView,
    BrandListView,
    BrandUpdateView,
    CategoryCreateView,
    CategoryDeleteView,
    CategoryListView,
    CategoryUpdateView,
    FormatoCreateView,
    FormatoDeleteView,
    FormatoListView,
    FormatoUpdateView,
    IndicacionesUsoCreateView,
    IndicacionesUsoDeleteView,
    IndicacionesUsoListView,
    IndicacionesUsoUpdateView,
    M2CajaCreateView,
    M2CajaDeleteView,
    M2CajaListView,
    M2CajaUpdateView,
    ProductCreateView,
    ProductDeleteView,
    ProductListView,
    ProductUpdateView,
)

app_name = "productos"

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("nuevo/", ProductCreateView.as_view(), name="create"),
    path("<int:pk>/editar/", ProductUpdateView.as_view(), name="update"),
    path("<int:pk>/eliminar/", ProductDeleteView.as_view(), name="delete"),
    path("categorias/", CategoryListView.as_view(), name="categories"),
    path("categorias/nueva/", CategoryCreateView.as_view(), name="category_create"),
    path("categorias/<int:pk>/editar/", CategoryUpdateView.as_view(), name="category_update"),
    path("categorias/<int:pk>/eliminar/", CategoryDeleteView.as_view(), name="category_delete"),
    path("marcas/", BrandListView.as_view(), name="brands"),
    path("marcas/nueva/", BrandCreateView.as_view(), name="brand_create"),
    path("marcas/<int:pk>/editar/", BrandUpdateView.as_view(), name="brand_update"),
    path("marcas/<int:pk>/eliminar/", BrandDeleteView.as_view(), name="brand_delete"),
    path("formatos/", FormatoListView.as_view(), name="formatos"),
    path("formatos/nuevo/", FormatoCreateView.as_view(), name="formato_create"),
    path("formatos/<int:pk>/editar/", FormatoUpdateView.as_view(), name="formato_update"),
    path("formatos/<int:pk>/eliminar/", FormatoDeleteView.as_view(), name="formato_delete"),
    path("acabados/", AcabadoListView.as_view(), name="acabados"),
    path("acabados/nuevo/", AcabadoCreateView.as_view(), name="acabado_create"),
    path("acabados/<int:pk>/editar/", AcabadoUpdateView.as_view(), name="acabado_update"),
    path("acabados/<int:pk>/eliminar/", AcabadoDeleteView.as_view(), name="acabado_delete"),
    path("indicaciones/", IndicacionesUsoListView.as_view(), name="indicaciones"),
    path("indicaciones/nueva/", IndicacionesUsoCreateView.as_view(), name="indicaciones_create"),
    path("indicaciones/<int:pk>/editar/", IndicacionesUsoUpdateView.as_view(), name="indicaciones_update"),
    path("indicaciones/<int:pk>/eliminar/", IndicacionesUsoDeleteView.as_view(), name="indicaciones_delete"),
    path("m2cajas/", M2CajaListView.as_view(), name="m2cajas"),
    path("m2cajas/nuevo/", M2CajaCreateView.as_view(), name="m2caja_create"),
    path("m2cajas/<int:pk>/editar/", M2CajaUpdateView.as_view(), name="m2caja_update"),
    path("m2cajas/<int:pk>/eliminar/", M2CajaDeleteView.as_view(), name="m2caja_delete"),
]
