# Generated by Django 6.0.4 on 2026-04-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='empresas.company', verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='almacenes.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='productos.product')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='proveedores.proveedor')),
            ],
            options={
                'unique_together': {('producto', 'almacen', 'lote')},
            },
        ),
    ]
