# Generated by Django 6.0.4 on 2026-04-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0003_alter_stock_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
