# Generated by Django 6.0.4 on 2026-04-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
