# Generated by Django 6.0.4 on 2026-05-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('ruc_nit', models.CharField(blank=True, max_length=30, verbose_name='RUC/NIT')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('currency', models.CharField(default='BOB', max_length=10, verbose_name='Moneda')),
                ('timezone', models.CharField(default='America/La_Paz', max_length=50, verbose_name='Zona horaria')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Configuracion del negocio',
                'ordering': ['name'],
            },
        ),
    ]
