# Generated by Django 6.0.4 on 2026-04-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='BOB', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='America/La_Paz', max_length=50, verbose_name='Zona horaria'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
